version: '3'
services:
    db:
        image: 'mysql'
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 2022@aidm
            MYSQL_DATABASE: aidm
            MYSQL_USER: aidm
            MYSQL_PASSWORD: 2022@aidm
            MYSQL_ALLOW_EMPTY_PASSWORD: ok
            MYSQL_ROOT_HOST: '%'
        volumes:
            - '../data:/var/lib/mysql'
        networks:
            - aidm
    pma:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8082:80
        restart: always
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 300M
            MYSQL_ROOT_PASSWORD: 'root'
        networks:
            - aidm
        depends_on:
          - db
    api:
        build:
            context: .
        restart: always
        ports:
            - '8081:80'
            - '9229:9229'
        command: npm run dev
        links:
            - db:db
        volumes:
            - '.:/app'
        networks:
            - aidm
        depends_on:
            - db
    # frontend:
    #     build:
    #         context: frontend/
    #     ports:
    #         - '8080:80'
    #     volumes:
    #         - './frontend:/app'
    #     networks:
    #         - aidm
networks:
    aidm:
        driver: bridge
# volumes:
#     db_data:
#         driver: local
