"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("aicenters", [
      {
        code: "01",
        name: "ศูนย์วิจัย ฯ สระบุรี",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "02",
        name: "ศูนย์วิจัย ฯ ชลบุรี",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "03",
        name: "ศูนย์วิจัย ฯ นครราชสีมา",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "04",
        name: "ศูนย์วิจัย ฯ ขอนแก่น",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "05",
        name: "ศูนย์วิจัย ฯ เชียงใหม่",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "06",
        name: "ศูนย์วิจัย ฯ พิษณุโลก",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "07",
        name: "ศูนย์วิจัย ฯ ราชบุรี",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "08",
        name: "ศูนย์วิจัย ฯ สุราษฏร์ธานี",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "09",
        name: "ศูนย์วิจัย ฯ สงขลา",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "10",
        name: "ศูนย์วิจัย ฯ อุบลราชธานี",
        sub_district_id: 1,
        district_id: 1,
        province_id: 1,
        postal_code: 1,
        email: "ddd@gmail.com",
        created_user_id: 1,
        created_datetime: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    // queryInterface.bulkDelete('organization_types', null, {});
  },
};
