"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("provinces", [
      {
        code: "10",
        name: "กรุงเทพมหานคร",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "11",
        name: "สมุทรปราการ",
        section_id: 1,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "12",
        name: "นนทบุรี",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "13",
        name: "ปทุมธานี",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "14",
        name: "พระนครศรีอยุธยา",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "15",
        name: "อ่างทอง",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "16",
        name: "ลพบุรี",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "17",
        name: "สิงห์บุรี",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "18",
        name: "ชัยนาท",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "19",
        name: "สระบุรี",
        section_id: 1,
        zone_id: 1,
        aicenter_id: 1,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "20",
        name: "ชลบุรี",
        section_id: 1,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "21",
        name: "ระยอง",
        section_id: 2,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "22",
        name: "จันทบุรี",
        section_id: 2,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "23",
        name: "ตราด",
        section_id: 2,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "24",
        name: "ฉะเชิงเทรา",
        section_id: 2,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "25",
        name: "ปราจีนบุรี",
        section_id: 2,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "26",
        name: "นครนายก",
        section_id: 2,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "27",
        name: "สระแก้ว",
        section_id: 2,
        zone_id: 2,
        aicenter_id: 2,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "30",
        name: "นครราชสีมา",
        section_id: 3,
        zone_id: 3,
        aicenter_id: 3,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "31",
        name: "บุรีรัมย์",
        section_id: 3,
        zone_id: 3,
        aicenter_id: 3,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "32",
        name: "สุรินทร์",
        section_id: 3,
        zone_id: 3,
        aicenter_id: 3,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "33",
        name: "ศรีสะเกษ",
        section_id: 3,
        zone_id: 3,
        aicenter_id: 10,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "34",
        name: "อุบลราชธานี",
        section_id: 3,
        zone_id: 3,
        aicenter_id: 10,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "35",
        name: "ยโสธร",
        section_id: 3,
        zone_id: 3,
        aicenter_id: 10,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "36",
        name: "ชัยภูมิ",
        section_id: 3,
        zone_id: 3,
        aicenter_id: 3,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "37",
        name: "อำนาจเจริญ",
        section_id: 3,
        zone_id: 3,
        aicenter_id: 10,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "38",
        name: "บึงกาฬ",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "39",
        name: "หนองบัวลำภู",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "40",
        name: "ขอนแก่น",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "41",
        name: "อุดรธานี",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "42",
        name: "เลย",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "43",
        name: "หนองคาย",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "44",
        name: "มหาสารคาม",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "45",
        name: "ร้อยเอ็ด",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "46",
        name: "กาฟสินธุ์",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 4,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "47",
        name: "สกลนคร",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 10,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "48",
        name: "นครพนม",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 10,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "49",
        name: "มุกดาหาร",
        section_id: 3,
        zone_id: 4,
        aicenter_id: 10,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "50",
        name: "เชียงใหม่",
        section_id: 4,
        zone_id: 5,
        aicenter_id: 5,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "51",
        name: "ลำพูน",
        section_id: 4,
        zone_id: 5,
        aicenter_id: 5,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "52",
        name: "ลำปาง",
        section_id: 4,
        zone_id: 5,
        aicenter_id: 5,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "53",
        name: "อุตรดิตถ์",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "54",
        name: "แพร่",
        section_id: 4,
        zone_id: 5,
        aicenter_id: 5,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "55",
        name: "น่าน",
        section_id: 4,
        zone_id: 5,
        aicenter_id: 5,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "56",
        name: "พะเยา",
        section_id: 4,
        zone_id: 5,
        aicenter_id: 5,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "57",
        name: "เชียงราย",
        section_id: 4,
        zone_id: 5,
        aicenter_id: 5,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "58",
        name: "แม่ฮ่องสอน",
        section_id: 4,
        zone_id: 5,
        aicenter_id: 5,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "60",
        name: "นครสวรค์",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "61",
        name: "อุทัยธานี",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "62",
        name: "กำแพงเพชร",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "63",
        name: "ตาก",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "64",
        name: "สุโขทัย",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "65",
        name: "พิษณุโลก",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "66",
        name: "พิจิตร",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "67",
        name: "เพชรบูรณ์",
        section_id: 4,
        zone_id: 6,
        aicenter_id: 6,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "70",
        name: "ราชบุรี",
        section_id: 4,
        zone_id: 7,
        aicenter_id: 7,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "71",
        name: "กาญจนบุรี",
        section_id: 4,
        zone_id: 7,
        aicenter_id: 7,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "72",
        name: "สุพรรณบุรี",
        section_id: 4,
        zone_id: 7,
        aicenter_id: 7,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "73",
        name: "นครปฐม",
        section_id: 4,
        zone_id: 7,
        aicenter_id: 7,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "74",
        name: "สมุทรสาคร",
        section_id: 4,
        zone_id: 7,
        aicenter_id: 7,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "75",
        name: "สมุทรสงคราม",
        section_id: 4,
        zone_id: 7,
        aicenter_id: 7,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "76",
        name: "เพชรบุรี",
        section_id: 4,
        zone_id: 7,
        aicenter_id: 7,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "77",
        name: "ประจวบคิรีขันธ์",
        section_id: 4,
        zone_id: 7,
        aicenter_id: 7,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "80",
        name: "นครศรีธรรมราช",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "81",
        name: "กระบี่",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "82",
        name: "พังงา",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "83",
        name: "ภูเก็ต",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "84",
        name: "สุราษฎร์ธานี",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "85",
        name: "ระนอง",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "86",
        name: "ชุมพร",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "90",
        name: "สงขลา",
        section_id: 4,
        zone_id: 9,
        aicenter_id: 9,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "91",
        name: "สตูล",
        section_id: 4,
        zone_id: 9,
        aicenter_id: 9,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "92",
        name: "ตรัง",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "93",
        name: "พัทลุง",
        section_id: 4,
        zone_id: 8,
        aicenter_id: 8,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "94",
        name: "ปัตตานี",
        section_id: 4,
        zone_id: 9,
        aicenter_id: 9,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "95",
        name: "ยะลา",
        section_id: 4,
        zone_id: 9,
        aicenter_id: 9,
        created_user_id: 1,
        created_datetime: new Date(),
      },{
        code: "96",
        name: "นราธิวาส",
        section_id: 4,
        zone_id: 9,
        aicenter_id: 9,
        created_user_id: 1,
        created_datetime: new Date(),
      }
    ]);
  },

  async down(queryInterface, Sequelize) {
    // queryInterface.bulkDelete('organization_types', null, {});
  },
};
